#+title: SmartDox DSLサンプル文書

SmartDox DSLを使って記述したモデルの
サンプル文書です。

文書でサンプルモデルの定義をします。
本来は文書中の仕様記述の文書は
定義するモデルに対するものになります。

しかし、この文書ではSmartDox DSLの記述例として
SmartDox DSL文法の説明を記述することにします。

* 使い方

本文書はSmartDoxで文書として、
SimpleModelerではモデルとして操作します。

** 文書をPDFで出力

SmartDoxを使ってPDF出力することができます。

#+begin_src console
$ dox -pdf sample.org
#+end_src

** クラス図を生成

SimpleModelerを使ってクラス図を生成することができます。

#+begin_src console
$ sm -diagram sample.org
#+end_src

** プログラムを生成

SimpleModelerを使ってプログラムを生成することができます。

#+begin_src console
$ sm -extjs sample.org
#+end_src

* 登場人物

「登場人物」の節ではアクターの定義を行います。

アクターの定義方法には以下の2つがあります。

- 一覧表で定義
- 節で定義

以下では表「登場人物一覧」でアクター「商店」を定義しています。

#+caption: 登場人物一覧
| 名前 |
|------|
| 商店 |

また、以下では節でアクター「顧客」を定義しています。

** 顧客

#+caption: 属性一覧
| 名前 | 型     | 多重度 |
|------+--------+--------|
| 名前 | string |      1 |
| 住所 | string |      1 |

*** 種類

インヘリタンスは「種類」の節の配下に
親となる登場人物の一種である登場人物を
一覧表または節で記述します。

**** 個人顧客

**** 法人顧客

* 道具

道具の節ではリソース・エンティティの定義を行います。

** 商品
*** 属性
**** 商品名
**** 定価(long)
*** 区分
**** 商品区分(第1類;第2類;第3類)

* 出来事

出来事の節ではイベント・エンティティの定義を行います。

登場人物や
イベント・エンティティの定義方法には以下の2つがあります。

- 一覧表で定義
- 節で定義

** 購入する

購入するはイベント・エンティティです。

*** 主役
**** 顧客
*** 相手役
**** 商店
*** 部品
**** 商品
